version: '3'
services:
  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/frontend:/src
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/FavSpot/src/backend:/home/ubuntu/FavSpot/src/backend

  web:
    build: .
    container_name: dg01
    ports:
      - '8443:8443'
    command: bash -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      daphne -e ssl:8443:privateKey=/src/privkey.pem:certKey=/src/cert.pem app.asgi:application -b 0.0.0.0"
    depends_on:
      - db
    volumes:
      - ./src/backend:/src

  db:
    image: postgres:14.8
    ports:
      - '5432:5432'
    container_name: ps01
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
