# Generated by Django 4.2.4 on 2023-08-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_pin_menu_pin_thumbnail_img_alter_pin_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='menu',
        ),
    ]
