# Generated by Django 4.2.4 on 2023-08-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='board.boardtag'),
        ),
    ]
