# Generated by Django 4.2.4 on 2023-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
