# Generated by Django 4.2.4 on 2023-08-20 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pin', '0001_initial'),
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincontent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pin',
            name='board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.category'),
        ),
        migrations.AddField(
            model_name='pin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
