# Generated by Django 4.2.4 on 2023-08-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincontent',
            name='pin_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pin.pin'),
        ),
    ]
