# Generated by Django 4.2.4 on 2023-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_remove_pin_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='place_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
